accounts_to_fund: 10
anvil_port: 8545
block_time: 1
burst_limit: 20
default_block_number: null
default_gas_limit: 3000000
default_gas_price: null
enable_mining: false
log_directory: logs/fork_testing
log_level: INFO
mainnet_rpc: https://eth-mainnet.g.alchemy.com/v2/xtYAM1LOYlQryoaMfPNjl
max_retries: 3
networks:
  mainnet:
    confirmations: 1
    enabled: true
    priority_fee: null
  testnet:
    confirmations: 1
    enabled: true
    priority_fee: null
requests_per_second: 10
retry_delay: 1.0
save_fork_logs: true
testnet_rpc: https://eth-goerli.g.alchemy.com/v2/xtYAM1LOYlQryoaMfPNjl
timeout: 300
