fuzzing:
  max_runs: 1000
  timeout: 300
  seed_generation:
    strategy: intelligent
    count: 50

  engines:
    - name: foundry
      enabled: true
      config:
        fuzz_runs: 1000
        coverage: true

    - name: anvil
      enabled: true
      config:
        fork_url: null
        block_number: latest

  targets:
    functions:
      - pattern: ".*"
        weight: 1.0

    state_variables:
      - pattern: "balance.*"
        weight: 0.8

  rewards:
    coverage_bonus: 0.1
    crash_bonus: 1.0
    vulnerability_bonus: 2.0

  validation:
    exploit_confirmation: true
    false_positive_filtering: true
