flow:
  - node: FileReaderNode
  - node: StaticAnalysisNode
  - node: LLMAnalysisNode
  - node: ValidationNode  # Always run validation step
  - node: ExploitValidatorNode
  - node: AetherFuzzRunner
  - node: ReportNode

tools:
  - name: slither
    type: static_analysis
    output_format: json
    enabled: true
    config:
      exclude_dependencies: false
      exclude_informational: false
      timeout: 600
      detectors: ["all"]

  - name: mythril
    type: symbolic_execution
    enabled: true
    config:
      solc_json: true
      output: json
      timeout: 600
      execution_timeout: 300

  - name: llm_gpt
    type: reasoning
    enabled: true
    model: gpt-5-chat-latest
    config:
      temperature: 0.2
      max_tokens: 2000
      system_prompt: |
        You are an expert smart contract security auditor specializing in DeFi protocols. 
        Analyze the provided Solidity code for:
        1. Critical vulnerabilities: reentrancy, access control, arithmetic issues
        2. DeFi-specific risks: liquidation logic, oracle manipulation, flash loan attacks
        3. Access control issues: unauthorized access, privilege escalation
        4. Input validation problems: missing checks, overflow/underflow
        5. Economic attacks: price manipulation, MEV, sandwich attacks
        Focus on high-impact vulnerabilities that could lead to fund loss or protocol insolvency.
        Provide specific line numbers and detailed explanations with confidence scores.

node_configs:
  FileReaderNode:
    include_line_numbers: true
    extract_metadata: true
    recursive_search: true

  StaticAnalysisNode:
    tools: [slither, mythril]
    severity_threshold: low
    output_format: structured
    focus_patterns: 
      - reentrancy
      - access_control
      - arithmetic
      - oracle_manipulation
      - liquidation_logic

  LLMAnalysisNode:
    analysis_types: [vulnerability_detection, defi_risks, access_control]
    confidence_threshold: 0.6
    llm_confirm_threshold: 0.7
    focus_areas:
      - defi_protocols
      - access_control
      - economic_attacks

  ValidationNode:
    retest_tools: [slither]
    validation_threshold: 0.8
    require_recompilation: true
    always_run: true  # Force validation to always run

  AetherFuzzRunner:
    max_runs: 2000
    timeout: 600
    seed_generation: intelligent
    coverage_tracking: true
    focus_functions:
      - deposit
      - withdraw
      - borrow
      - repay

  ExploitValidatorNode:
    generate_pocs: true
    validate_exploits: true
    focus_severities: [critical, high, medium]
    include_gas_estimates: true

  ReportNode:
    format: markdown
    include_details: true
    output_sections: [summary, vulnerabilities, exploits, fixes, recommendations, validation]
    bug_bounty_format: true
    immunefi_compatible: true
